version: '3'

services:
  # MySQL service
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: tanX
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3500:3306"

  # Flask application service
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db:3306/tanX
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0


